"""Bando de dados Postgree

Revision ID: 037aeaeb52a0
Revises: 58bfd26ed3ec
Create Date: 2026-03-30 17:48:33.751830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037aeaeb52a0'
down_revision: Union[str, Sequence[str], None] = '58bfd26ed3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
