"""criando tabela aula atualizacao

Revision ID: 2e26543bc63f
Revises: a1144f9e989c
Create Date: 2026-06-15 08:14:17.335468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e26543bc63f'
down_revision: Union[str, Sequence[str], None] = 'a1144f9e989c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('caminho_arquivo', sa.String(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aulas_id'), 'aulas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aulas_id'), table_name='aulas')
    op.drop_table('aulas')
    # ### end Alembic commands ###
