"""Atualizacao do banco de dados

Revision ID: 58bfd26ed3ec
Revises: 6671cc46dfb4
Create Date: 2026-03-28 17:59:01.753320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58bfd26ed3ec'
down_revision: Union[str, Sequence[str], None] = '6671cc46dfb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
