"""Correcao do back_populates

Revision ID: a1144f9e989c
Revises: 037aeaeb52a0
Create Date: 2026-06-12 08:34:42.483265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1144f9e989c'
down_revision: Union[str, Sequence[str], None] = '037aeaeb52a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nome_user', sa.String(), nullable=False))
    op.drop_index(op.f('ix_users_nome_adm'), table_name='users')
    op.create_index(op.f('ix_users_nome_user'), 'users', ['nome_user'], unique=True)
    op.drop_column('users', 'nome_adm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nome_adm', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_nome_user'), table_name='users')
    op.create_index(op.f('ix_users_nome_adm'), 'users', ['nome_adm'], unique=True)
    op.drop_column('users', 'nome_user')
    # ### end Alembic commands ###
